[package]
name = "rinputer4_5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
dogd = { git = "https://github.com/R-ARM/dogd.git", version = "0.1.0" }
evdev = "0.12.1"
